"""add_username_make_email_optional

Revision ID: 46d802c5b8ff
Revises: e1e7456c65fd
Create Date: 2026-03-02 09:25:38.314056

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = '46d802c5b8ff'
down_revision = 'e1e7456c65fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # 1. Add username column (nullable first so existing rows don't break)
    op.add_column('users', sa.Column('username', sa.String(length=60), nullable=True))

    # 2. Populate username from email (part before @)
    op.execute("UPDATE users SET username = split_part(email, '@', 1)")

    # 3. Make username NOT NULL now that all rows are populated
    op.alter_column('users', 'username', nullable=False)

    # 4. Add unique index
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)

    # 5. Make email optional
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=320),
               nullable=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=320),
               nullable=False)
    op.drop_column('users', 'username')
    # ### end Alembic commands ###

