"""Add book_finished and comment to reading_logs

Revision ID: 90f5e384b67f
Revises: ca9b56a08d49
Create Date: 2026-02-27 11:47:48.251120

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = '90f5e384b67f'
down_revision = 'ca9b56a08d49'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_groups_slug'), 'groups', type_='unique')
    op.add_column('reading_logs', sa.Column('book_finished', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('reading_logs', sa.Column('comment', sa.Text(), nullable=True))
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('reading_logs', 'comment')
    op.drop_column('reading_logs', 'book_finished')
    op.create_unique_constraint(op.f('uq_groups_slug'), 'groups', ['slug'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###

