"""non nullable gender

Revision ID: ca9b56a08d49
Revises: 20260117_0002
Create Date: 2026-01-18 20:51:21.855611

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = 'ca9b56a08d49'
down_revision = '20260117_0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE users SET gender = 'male' WHERE gender IS NULL")
    op.alter_column('users', 'gender',
               existing_type=postgresql.ENUM('male', 'female', name='gender'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'gender',
               existing_type=postgresql.ENUM('male', 'female', name='gender'),
               nullable=True)
    # ### end Alembic commands ###

