"""add telegram_id to users

Revision ID: e1e7456c65fd
Revises: 90f5e384b67f
Create Date: 2026-02-28 22:13:31.403247

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = 'e1e7456c65fd'
down_revision = '90f5e384b67f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_id', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_id')
    # ### end Alembic commands ###

