export { HomePage } from './home';
export { ForgotPasswordPage } from './forgot-password';
export { LoginPage } from './login';
export { ClaimPage } from './claim';
export { RegisterPage } from './register';
export { DashboardPage } from './dashboard';
export { ArchivePage } from './archive';
export { ResultsPage } from './results';
export { ProfilePage } from './profile';
export { InsightsPage } from './insights';
export { HallOfFamePage } from './hall-of-fame';
export { DirectoryPage } from './directory';
export { PublicProfilePage } from './reader';
export { SuggestionsPage } from './suggestions';
export { AdminSuggestionsPage } from './admin-suggestions';
export { PrivacyPage, TermsPage } from './legal';
